---
- name: Add 1Password APT signing key
  become: true
  ansible.builtin.shell:
    cmd: curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
    creates: /usr/share/keyrings/1password-archive-keyring.gpg

- name: Add 1Password APT repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_architecture | regex_replace('x86_64', 'amd64') }} signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/{{ ansible_architecture | regex_replace('x86_64', 'amd64') }} stable main"
    filename: 1password
    state: present

- name: Create debsig policy directory
  become: true
  ansible.builtin.file:
    path: /etc/debsig/policies/AC2D62742012EA22
    state: directory
    mode: '0755'

- name: Download debsig policy
  become: true
  ansible.builtin.get_url:
    url: https://downloads.1password.com/linux/debian/debsig/1password.pol
    dest: /etc/debsig/policies/AC2D62742012EA22/1password.pol
    mode: '0644'

- name: Create debsig keyring directory
  become: true
  ansible.builtin.file:
    path: /usr/share/debsig/keyrings/AC2D62742012EA22
    state: directory
    mode: '0755'

- name: Add 1Password debsig keyring
  become: true
  ansible.builtin.shell:
    cmd: curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
    creates: /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
