---
apt_keys:
  - url: https://mise.jdx.dev/gpg-key.pub
    keyring: /etc/apt/keyrings/mise.gpg

apt_repositories:
  - repo: "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.pub arch=amd64] https://mise.jdx.dev/deb stable main"
    filename: mise

packages:

  - build-essential
  - curl
  - eza
  - fd-find
  - gh
  - git-delta
  - htop
  - htop
  - liblua5.4-dev
  - lua5.4
  - mise
  - podman
  - qemu-system
  - ripgrep
  - stow
  - tmux
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting

snaps:
  - steam
