[tools]
go = "latest"
rust = { version = "beta", components = "rust-src,rust-analyzer" }
"cargo:https://github.com/simonrw/cftail" = "branch:main"
"cargo:https://github.com/simonrw/testsearch" = "branch:main"
"go:github.com/simonrw/cert-info" = "0"
"github:atuinsh/atuin" = { version = "latest", os = ["linux"], asset_pattern = "atuin-x86_64-unknown-linux-gnu.tar.gz" }
"github:jj-vcs/jj" = { version = "latest", os = ["linux"] }
"cargo:https://github.com/simonrw/listprojects" = "branch:main"
"github:tmux/tmux-builds" = { version = "latest", os = ["linux"] }
fzf = { version = "latest", os = ["linux"] }
node = { version = "lts", os = ["linux"] }
"npm:@anthropic-ai/claude-code" = { version = "latest", os = ["linux"] }
"github:sachaos/viddy" = { version = "latest", os = ["linux"] }
"github:sharkdp/bat" = { version = "latest", os = ["linux"] }
"github:bootandy/dust" = { version = "latest", os = ["linux"] }
"cargo:zoxide" = { version = "latest", os = ["linux"] }
"cargo:worktrunk" = { version = "latest", os = ["linux"] }
bun = { version = "latest", os = ["linux"] }
usage = { version = "latest", os = ["linux"] }
"github:lima-vm/lima" = { version = "latest", os = ["linux"] }
"cargo:mergiraf" = { version = "latest", os = ["linux"] }
jless = { version = "latest", os = ["linux"] }
gh = { version = "latest", os = ["linux"] }
uv = { version = "latest", os = ["linux"] }
jjui = { version = "latest", os = ["linux"] }

[tools."github:MordechaiHadad/bob"]
version = "latest"
os = ["linux"]

[tools."github:MordechaiHadad/bob".platforms]
linux-x64 = { asset_pattern = "bob-linux-x86_64-openssl.zip" }
macos-arm64 = { asset_pattern = "bob-macos-arm.zip" }

[settings]
experimental = true
# support .python-version files in Python
# required for LocalStack
idiomatic_version_file_enable_tools = ["python", "rust"]
lockfile = true
