[tools]
rust = { version = "beta", components = "rust-src,rust-analyzer" }
"cargo:https://github.com/simonrw/cftail" = "branch:main"
"cargo:https://github.com/cloudflare/networkquality-rs" = "branch:main"
"cargo:https://github.com/simonrw/testsearch" = "branch:main"
"go:github.com/simonrw/cert-info" = "0"
"cargo:https://github.com/simonrw/listprojects" = "branch:main"
"npm:@sourcegraph/amp" = "latest"

[settings]
experimental = true
# support .python-version files in Python
# required for LocalStack
idiomatic_version_file_enable_tools = ["python", "rust"]
lockfile = true
